/// Generated by https://quicktype.io

#[derive(Serialize, Deserialize)]
pub struct CoronaData {
    #[serde(rename = "summaryStats")]
    pub summary_stats: SummaryStats,

    #[serde(rename = "cache")]
    pub cache: Cache,

    #[serde(rename = "dataSource")]
    pub data_source: DataSource,

    #[serde(rename = "apiSourceCode")]
    pub api_source_code: String,

    #[serde(rename = "rawData")]
    pub raw_data: Vec<RawDatum>,
}


#[derive(Serialize, Deserialize)]
pub struct Cache {
    #[serde(rename = "lastUpdated")]
    pub last_updated: String,

    #[serde(rename = "expires")]
    pub expires: String,

    #[serde(rename = "lastUpdatedTimestamp")]
    pub last_updated_timestamp: i64,

    #[serde(rename = "expiresTimestamp")]
    pub expires_timestamp: i64,
}

#[derive(Serialize, Deserialize)]
pub struct DataSource {
    #[serde(rename = "url")]
    pub url: String,

    #[serde(rename = "lastGithubCommit")]
    pub last_github_commit: String,

    #[serde(rename = "mostRecentData")]
    pub most_recent_data: String,

    #[serde(rename = "publishedBy")]
    pub published_by: String,

    #[serde(rename = "ref")]
    pub data_source_ref: String,
}


#[derive(Serialize, Deserialize)]
pub struct RawDatum {
    #[serde(rename = "Province/State")]
    pub province_state: String,

    #[serde(rename = "Country/Region")]
    pub country_region: String,

    #[serde(rename = "Last Update")]
    pub last_update: String,

    #[serde(rename = "Confirmed")]
    pub confirmed: String,

    #[serde(rename = "Deaths")]
    pub deaths: String,

    #[serde(rename = "Recovered")]
    pub recovered: String,

    #[serde(rename = "Latitude")]
    pub latitude: String,

    #[serde(rename = "Longitude")]
    pub longitude: String,
}


#[derive(Serialize, Deserialize)]
pub struct SummaryStats {
    #[serde(rename = "global")]
    pub global: China,

    #[serde(rename = "china")]
    pub china: China,

    #[serde(rename = "nonChina")]
    pub non_china: China,
}


#[derive(Serialize, Deserialize)]
pub struct China {
    #[serde(rename = "confirmed")]
    pub confirmed: i64,

    #[serde(rename = "recovered")]
    pub  recovered: i64,

    #[serde(rename = "deaths")]
    pub deaths: i64,
}
